version: 2
models: 
  - name: stg_customer
    description: staging customers table

    columns:
      - name: id
        description: id column name
  - name: stg_employee
    description: staging employees
    columns:
      - name: id
      - name: company
  - name: orders_status_full
    description: staging orders with status 
    columns:
      - name: order_id
      - name: employee_id
      - name: customer_id
      - name: status_name